name: ikaros
description: ikaros app by flutter
version: 15.3.23

environment:
  sdk: '>=2.18.4 <=3.10.5'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.8
  cupertino_icons: ^1.0.2
  dio: ^5.3.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.0
  flutter_easyrefresh: ^2.2.2
  path_provider: ^2.0.15
  uuid: ^3.0.7
  flutter_vlc_player:
    path: dependencies/flutter_vlc_player/flutter_vlc_player
  provider: ^6.0.5
  dart_vlc:
    path: dependencies/dart_vlc
  audio_video_progress_bar: ^2.0.3
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.2
  open_file: ^3.3.2
  permission_handler: ^11.3.1
  win32: ^5.5.4
  desktop_window: ^0.4.0
  ffi: ^2.1.3
  ns_danmaku:
    path: dependencies/ns_danmaku
  synchronized: ^3.2.0
  crypto: ^3.0.5
  wakelock_plus: ^1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.17.0
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
