name: ikaros
description: ikaros app by flutter
version: 1.7.2

environment:
  sdk: '>=3.12.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^9.1.0
  cupertino_icons: ^1.0.9
  dio: ^5.10.0
  json_annotation: ^4.12.0
  shared_preferences: ^2.5.5
  flutter_easyrefresh: ^2.2.2
  path_provider: ^2.1.6
  uuid: ^3.0.7
  flutter_vlc_player:
    path: dependencies/flutter_vlc_player/flutter_vlc_player
  provider: ^6.1.5
  dart_vlc:
    path: dependencies/dart_vlc
  audio_video_progress_bar: ^2.0.3
  url_launcher: ^6.3.2
  package_info_plus: ^8.3.0
  open_file: ^3.5.10
  permission_handler: 12.0.3
  win32: ^5.10.1
  desktop_window: ^0.4.4
  ffi: ^2.2.0
  ns_danmaku:
    path: dependencies/ns_danmaku
  synchronized: ^3.4.1
  crypto: ^3.0.7
  wakelock_plus: ^1.2.11
  just_audio: ^0.9.46
  photo_manager: ^3.9.0
  app_links: ^6.4.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.31.0
  flutter_lints: ^6.0.0
  json_serializable: ^6.14.0
  build_runner: ^2.15.1

flutter:
  uses-material-design: true
  assets:
    - assets/loading.gif
