import 'package:json_annotation/json_annotation.dart';

enum EpisodeGroup {
  @JsonValue("MAIN")
  MAIN,
  @JsonValue("PROMOTION_VIDEO")
  PROMOTION_VIDEO,
  @JsonValue("OPENING_SONG")
  OPENING_SONG,
  @JsonValue("ENDING_SONG")
  ENDING_SONG,
  @JsonValue("SPECIAL_PROMOTION")
  SPECIAL_PROMOTION,
  @JsonValue("SMALL_THEATER")
  SMALL_THEATER,
  @JsonValue("LIVE")
  LIVE,
  @JsonValue("COMMERCIAL_MESSAGE")
  COMMERCIAL_MESSAGE,
  @JsonValue("ORIGINAL_SOUND_TRACK")
  ORIGINAL_SOUND_TRACK,
  @JsonValue("ORIGINAL_VIDEO_ANIMATION")
  ORIGINAL_VIDEO_ANIMATION,
  @JsonValue("ORIGINAL_ANIMATION_DISC")
  ORIGINAL_ANIMATION_DISC,
  @JsonValue("MUSIC_DIST1")
  MUSIC_DIST1,
  @JsonValue("MUSIC_DIST2")
  MUSIC_DIST2,
  @JsonValue("MUSIC_DIST3")
  MUSIC_DIST3,
  @JsonValue("MUSIC_DIST4")
  MUSIC_DIST4,
  @JsonValue("MUSIC_DIST5")
  MUSIC_DIST5,
  @JsonValue("OTHER")
  OTHER;

}