# This is a basic workflow to help you get started with Actions

name: Build Package

# Controls when the workflow will run
on:
  release:
    types: [published]

jobs:

  build_linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Git submodule init
        uses: snickerbockers/submodules-init@v4

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'
          channel: 'stable'

      - name: Restore packages
        run: flutter pub get

      - name: Enable linux desktop
        run: flutter config --enable-linux-desktop

      - name: Build Linux App Bundle
        run: flutter build linux --release

      - name: Create a tarball
        env:
          APP_NAME: $(ls build/linux/x64/release/bundle | grep .out | sed 's/.out//')
          VERSION: ${{ github.ref_name }}
        run: |
          mkdir -p build/linux/x64/release/${APP_NAME}
          cp -r build/linux/x64/release/bundle/* build/linux/x64/release/${APP_NAME}/
          tar -czvf build/linux/x64/release/${APP_NAME}-linux.tar.gz -C build/linux/x64/release ${APP_NAME}
          
          cat <<EOF > build/linux/x64/release/${APP_NAME}/DEBIAN/control
          Package: ${APP_NAME}
          Version: ${VERSION}
          Section: base
          Priority: optional
          Architecture: amd64
          Depends: libgtk-3-0, libstdc++6
          Maintainer: Chivehao <chivehao@ikaros.run>
          Description: Ikaros flutter app.
          EOF

      - name: Publish Linux Artefacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.LI_GUOHAO_TOKEN }}
          file: build/linux/x64/release/${{ env.APP_NAME }}-linux.tar.gz
          asset_name: ikaros-linux-${{  github.ref_name }}.tar.gz

      - name: Build DEB package
        run: |
          APP_NAME=$(ls build/linux/x64/release/bundle | grep .out | sed 's/.out//')
          dpkg-deb --build build/linux/x64/release/${APP_NAME}

      - name: Publish DEB Linux/Ubuntu Artefacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.LI_GUOHAO_TOKEN }}
          file: build/linux/x64/release/${{ env.APP_NAME }}.deb
          asset_name: ikaros-ubuntu-${{  github.ref_name }}.deb


