# This is a basic workflow to help you get started with Actions

name: Build Macos Package

# Controls when the workflow will run
on:
  release:
    types: [published]

jobs:
  build_macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Git submodule init
        uses: snickerbockers/submodules-init@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build macOS app
        run: flutter build macos --release

      - name: Find the generated .app file
        id: find_app
        run: echo "APP_NAME=$(ls build/macos/Build/Products/Release/ | grep .app)" >> $GITHUB_ENV

      - name: Create DMG installer
        run: |
          mkdir -p build/macos/Build/Products/Release/dmg
          hdiutil create build/macos/Build/Products/Release/dmg/${{ env.APP_NAME }}-macOS.dmg \
            -volname "IkarosApp Installer" \
            -srcfolder build/macos/Build/Products/Release/${{ env.APP_NAME }} \
            -ov -format UDZO

      - name: Publish Macos Artefacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.LI_GUOHAO_TOKEN }}
          file: build/macos/Build/Products/Release/dmg/${{ env.APP_NAME }}-macOS.dmg
          asset_name: ikaros-macOS-${{ github.ref_name }}.dmg



