# This is a basic workflow to help you get started with Actions

name: Build Windows Package

# Controls when the workflow will run
on:
  release:
    types: [published]

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Git submodule init
        uses: snickerbockers/submodules-init@v4

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'
          channel: 'stable'

      - name: Restore packages
        run: flutter pub get

      - name: Build Android App Bundle
        run: flutter build windows --release

      - name: Zip release files
        run: Compress-Archive -Path "build\\windows\\x64\\runner\\Release\\*" -DestinationPath "output.zip"

      - name: Publish Windows Artefacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.LI_GUOHAO_TOKEN }}
          file: output.zip
          asset_name: ikaros-windows-${{  github.ref_name }}.zip



