# This is a basic workflow to help you get started with Actions

name: Build Package

# Controls when the workflow will run
on:
  release:
    types: [published]

jobs:

  build_ios:
    runs-on: macos-latest
    env:
      SHEME: Runner
      BUILD_CONFIGURATION: Release

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'
          channel: 'stable'

      - name: Restore packages
        run: flutter pub get --disable-telemetry

      - name: Build Flutter
        run: flutter build ios --release --no-codesign

      - name: Build xArchive
        run: |
          mkdir Payload && mv build/ios/iphoneos/Runner.app Payload && zip -r Payload.zip Payload && mkdir output && mv Payload.zip output/ikaros.ipa

      - name: Upload ipa to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.LI_GUOHAO_TOKEN }}
          name: release-ios-${{  github.ref_name }}
          path: output

  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup Java to compile Android project
        uses: actions/setup-java@v1
        with:
          java-version: '17.x'

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'
          channel: 'stable'

      - name: Restore packages
        run: flutter pub get --disable-telemetry

      - name: Build Android App Bundle
        run: flutter build apk --release

      - name: Publish Android Artefacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.LI_GUOHAO_TOKEN }}
          name: release-android-${{  github.ref_name }}
          path: build/app/outputs/flutter-apk


