name: Create Draft Release

permissions:
  contents: write
  packages: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          # (Optional)
          changelog: CHANGELOG.MD
          draft: false
          # (Optional) Format of title.
          # [default value: $tag]
          # [possible values: variables $tag, $version, and any string]
          title: v$version
          # (Required) GitHub token for creating GitHub Releases.
          token: ${{ secrets.LI_GUOHAO_TOKEN }}
