name: Flutter_iOS

on:
  push:
    branches:
      - release-*
    tags:
      - '*'

jobs:
  build_ios:
    runs-on: macos-latest
    env:
      SHEME: Runner
      BUILD_CONFIGURATION: Release

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'

      - name: Restore packages
        run: flutter pub get

      - name: Build Flutter
        run: flutter build ios --release --no-codesign

      - name: Build xArchive
        run: |
          mkdir Payload && mv build/ios/iphoneos/Runner.app Payload && zip -r Payload.zip Payload && mkdir output && mv Payload.zip output/ikaros.ipa

      - name: Publish iOS Artefacts
        uses: actions/upload-artifact@v1
        with:
          name: release-ios-${{  github.ref_name }}
          path: output

      - name: Rename ipa file
        run: mv output/ikaros.ipa ikaros-v${{  github.ref_name }}.ipa
      - name: Init LanZouCloud-CMD
        run: |
          git clone https://github.com/zaxtyson/LanZouCloud-CMD.git && cd LanZouCloud-CMD && python3 -m pip install -r requirements.txt && python3 main.py
      - name: Publish IPA LanZouCloud
        run: |
          login ${{ secrets.LANZOUCLOUD_COOKIE }} && cd Ikaros/App/ipa && upload ikaros-v${{  github.ref_name }}.ipa && logout && bye